// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGlXoQN5FHMtaMsgM3XqOnZMX9zLIxlr8',
    appId: '1:406408015167:web:008bda8577ccfe4e0a378a',
    messagingSenderId: '406408015167',
    projectId: 'thuexethongbao',
    authDomain: 'thuexethongbao.firebaseapp.com',
    storageBucket: 'thuexethongbao.firebasestorage.app',
    measurementId: 'G-C8NTHR8X97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbBcuuxVtBCwgWEOdCHJQfCcex1p_LmW0',
    appId: '1:406408015167:android:1b2e1756e645d70a0a378a',
    messagingSenderId: '406408015167',
    projectId: 'thuexethongbao',
    storageBucket: 'thuexethongbao.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTW5AtpqqpgkkgjRaCS6utoZAmkBnR6r8',
    appId: '1:406408015167:ios:42000765c9a89b6a0a378a',
    messagingSenderId: '406408015167',
    projectId: 'thuexethongbao',
    storageBucket: 'thuexethongbao.firebasestorage.app',
    iosBundleId: 'com.example.duantotnghiepAppThueXe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTW5AtpqqpgkkgjRaCS6utoZAmkBnR6r8',
    appId: '1:406408015167:ios:42000765c9a89b6a0a378a',
    messagingSenderId: '406408015167',
    projectId: 'thuexethongbao',
    storageBucket: 'thuexethongbao.firebasestorage.app',
    iosBundleId: 'com.example.duantotnghiepAppThueXe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGlXoQN5FHMtaMsgM3XqOnZMX9zLIxlr8',
    appId: '1:406408015167:web:de42d0a40c1895ea0a378a',
    messagingSenderId: '406408015167',
    projectId: 'thuexethongbao',
    authDomain: 'thuexethongbao.firebaseapp.com',
    storageBucket: 'thuexethongbao.firebasestorage.app',
    measurementId: 'G-QNX1SGQHWW',
  );
}
